POST  http://localhost:3000/user/create 
Content-Type: application/json

{
    "name": "Eliab Bernardino",
    "nick": "Storme2107",
    "email": "Eliab2107@gmail.com",
    "password": "eueueu"
}

###

POST  http://localhost:3000/user/create 
Content-Type: application/json

{
    "name": "Eliane de Paula",
    "nick": "LordTrin21",
    "email": "Eliab2107@gmail.com",
    "password": "eueueu"
}
###


POST  http://localhost:3000/user/create 
Content-Type: application/json

{
    "name": "Eliab Bernardino",
    "nick": "Zombie10",
    "email": "Eliab2107@gmail.com",
    "password": "eueueu"
}

###
DELETE http://localhost:3000/user/delete 
Content-Type: application/json 

{
    "password": "eueueu",
    "id": 2
}


###
PATCH http://localhost:3000/user/changepassword
Content-Type: application/json 

{
    "password": "eueueu",
    "id": 4,
    "newPassword": "eueutu"
}
###
PATCH http://localhost:3000/user/changenick
Content-Type: application/json 

{
    "id": 2,
    "newNick": "zombie 11",
    "password": "eueueu"
}
###
POST  http://localhost:3000/posts/create 
Content-Type: application/json

{
    "userId": 2,
    "userNick": "LordTrin21",
    "text": "Meu pimeiro Post glr"
}

###
POST  http://localhost:3000/posts/create 
Content-Type: application/json

{
    "userId": 1,
    "userNick": "Storme2107",
    "text": "Meu segundo Post glr"
}

###
POST  http://localhost:3000/create 
Content-Type: application/json

{
    "userId": 1,
    "userNick": "Storme2107",
    "text": "Meu terceito Post glr"
}
###
POST  http://localhost:3000/create 
Content-Type: application/json

{
    "userId": 1,
    "userNick": "Eliab Bernardino",
    "text": "Meu quarto Post glr"
}

###
DELETE   http://localhost:3000/posts/delete
Content-Type: application/json

{
    "id": 4,
    "userId": 2,
    "userNick" "LordTrin21"
}


###
GET   http://localhost:3000/getall
Content-Type: application/json

{
    "userId":1
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "nick": "Storme2107",
    "password": "eueueu"
}
###
POST http://localhost:3000/user/logout
